### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nevasini** [Tech-Matrix/Wolfie-Discord-Bot#4]
The bug is reported because currently there is only one book in the database which is harry potter can be resolved by adding more books.

**Comment by A-HK** [comment]
Hey @nevasini , maybe you'd actually want to fill in the details in the template above as to what exactly the bug is xD?

**Comment by nevasini** [comment]
Yeah sure I will wait is this auto-email or smth?

**Comment by A-HK** [comment]
Yup yup it is ! Notifs from GitHub also come through email

**Comment by nevasini** [comment]
The bug is reported because currently there is only one book in the database which is harry potter can be resolved by adding more books.

**Comment by nevasini** [comment]
The bug is that only one book database is stored need to expand it

To Reproduce Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior A clear and concise description of what you expected to happen.

Screenshots If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]
Smartphone (please complete the following information):

Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Browser [e.g. stock browser, safari]
Version [e.g. 22]
Additional context Add any other context about the problem here.

**Comment by charvibannur** [comment]
I've assigned it. So you plan on incorporating more books right?

**Comment by A-HK** [comment]
Fixed in #7 . Closing this.
